<?php

/**
 * @file
 * The main module file.
 *
 * Code taken from @link post by jeremypeter @endlink.
 *
 * @link https://www.drupal.org/forum/support/module-development-and-code-questions/2015-06-03/drupal-8-override-template-with#comment-12159763 @endlink
 */

include_once 'includes/functions.inc';
include_once 'includes/processing.inc';
include_once 'includes/alters.inc';

/**
 * Implements hook_theme().
 */
function paragraphs_columns_theme() {

  $theme_templates = [];
  $paragraph_types = _paragraphs_columns_get_paragraph_types();

  foreach ($paragraph_types as $type) {
    $theme_templates['paragraph__paragraphs_columns__' . $type] = [
      'base hook' => 'paragraph',
    ];
  }

  $theme_templates['paragraphs_columns'] = [
    'base hook' => 'paragraph',
  ];

  $theme_templates['paragraphed_page'] = [
    'base hook' => 'page',
    'render element' => 'page',
  ];

  return $theme_templates;
}
