<?php

/**
 * @file
 * Contains paragraphs_columns_images.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function paragraphs_columns_images_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the paragraphs_columns_images module.
    case 'help.page.paragraphs_columns_images':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Paragraphs Columns Images') . '</p>';
      return $output;

    default:
  }
}
