<?php

/**
 * @file
 * Contains paragraphs_columns_images.module.
 */

include_once 'includes/functions.inc';

/**
 * Implements hook_theme().
 */
function paragraphs_columns_images_theme() {

  $theme_templates = [];
  $paragraph_types = _paragraphs_columns_images_get_paragraph_types();

  foreach ($paragraph_types as $type) {
    $theme_templates['paragraph__paragraphs_columns__' . $type] = [
      'base hook' => 'paragraph',
    ];
  }

  $theme_templates['paragraphs_columns'] = [
    'base hook' => 'paragraph',
  ];

  $theme_templates['paragraphed_page'] = [
    'base hook' => 'page',
    'render element' => 'page',
  ];

  return $theme_templates;
}
